### ISSUE TITLE
Support for -n or --no-verify option

### ISSUE THREAD

**Issue by ethyde** [BigstickCarpet/version-bump-prompt#24]
Hello,

I started using this module as a remplacement for `npm/standard version`, but in my workflow we use [commitlint](https://github.com/marionebl/commitlint) to ensure well formated commit message.

And when i prepare a release, and because i don't need to lint my commit message, i can use [`--no-verif`](https://git-scm.com/docs/git-commit#git-commit---no-verify) to bypass linting.

At this moment i have found a workaround with [git-branch-is](https://github.com/kevinoid/git-branch-is) to check the branch name, but i think it would be cool to add this option.

Thanks !

**Comment by JamesMessinger** [comment]
Fixed by PR #31
