### ISSUE TITLE
Make git tag prefix "v" optional.

### ISSUE THREAD

**Issue by ethyde** [BigstickCarpet/version-bump-prompt#25]
Hello,

I noticed that git tags are prefixed with the letter "v" but this is not the case for package.json.

In some workflows we need git tags and npm versions to be identical.

So, it may be practical to be able to standardize both.

Thanks.

**Comment by JamesMessinger** [comment]
I just released [**version 5.0.0**](https://github.com/JS-DevTools/version-bump-prompt/blob/master/CHANGELOG.md), which resolves this issue.
