### ISSUE TITLE
[Feature] Support no-bump option

### ISSUE THREAD

**Issue by perry-mitchell** [BigstickCarpet/version-bump-prompt#28]
I use this package in a lot of projects, and it's terribly convenient, but one item which is missing in my opinion is the ability to specify a no-bump option. Sometimes a deployment fails due to some network condition in one of our projects and we'd simply like to deploy the bumped version.. It'd be great if there were a flag for such an option within `version-bump-prompt`, such as `--allow-no-bump` or `--opt-bypass`, for example.

As `version-bump-prompt` is usually always the first step for me, having such a feature would mean that I wouldn't need to add another prompt _before_ this one.

EDIT: I'd happily add this if it's something you'd be interested in.

**Comment by JamesMessinger** [comment]
Thanks for the suggestion!  I'm glad you find this tool useful.  

I assume you're using the `--prompt` option, right?  If so, then how about we just add another option to the prompt list to leave the version number the same.  For example, the prompt might look like this:

```
Current version in package.json is 2.7.0
How would you like to bump it?
  major (3.0.0)
  minor (2.8.0)
> patch (2.7.1)
  pre-release major (3.0.0-beta.0)
  pre-release minor (2.8.0-beta.0)
  pre-release patch (2.7.1-beta.0)
  pre-release (2.7.1-beta.0)
  no version change (2.7.0)
```

Notice the `no version change` option at the end.  Would that solve your need?

**Comment by perry-mitchell** [comment]
That'd be amazing! It's exactly what I'm after, yes.

Would you want to do it or would you take a PR? I'm happy either way of course.

**Comment by JamesMessinger** [comment]
I'd be happy to accept a PR!  Thanks!

**Comment by JamesMessinger** [comment]
Just to make sure we're on the same page... I **don't** think this requires any new command-line option (like `--allow-no-bump` or `--opt-bypass`).  I think this is just an enhancement to the existing `--prompt`  functionality

**Comment by JamesMessinger** [comment]
@perry-mitchell - I was just looking at the code and noticed that this functionality already exists 🤦‍♂️

The `--prompt` option includes a `custom...` option that lets you specify whatever version number you want, and it defaults to the current version.

**Comment by perry-mitchell** [comment]
@JamesMessinger Good point! I saw this as well. I’m not sure that it’s super clear however, and having it as an option would mean less work in those workflows.

What’s your opinion in this regard?

**Comment by perry-mitchell** [comment]
Maybe the custom item is enough for now. It's not super clear but seems to do the job. Thanks!

**Comment by JamesMessinger** [comment]
@perry-mitchell - I'm currently working on a complete rewrite of version-bump-prompt.  It's almost done, and it will include a "leave as-is" option in addition to the "custom" option.  Expect to see it soon.
