### ISSUE TITLE
[feature request] Customise commit message

### ISSUE THREAD

**Issue by jmatsushita** [BigstickCarpet/version-bump-prompt#3]
Hi there,

It would be nice to be able to customise the beginning of the commit message. And I just saw that the @octoblu fork by @sqrtofsaturn actually does this  in its [v1.6.1](https://github.com/BigstickCarpet/version-bump-prompt/compare/master...octoblu:master)

I'm creating a pull request!

Jun

**Comment by JamesMessinger** [comment]
Thanks!  Great new feature!  Merged it like a boss. ;)
