### ISSUE TITLE
Version number added to beginning of commit message

### ISSUE THREAD

**Issue by RTSchriner** [BigstickCarpet/version-bump-prompt#30]
The version number is added to the beginning of the commit message instead of the end.

**Steps to recreate:**
1. NPM package.json version is `v1.7.0-alpha.0`
2. Run `bump --preminor --lock --commit 'Upgrading to v'`
3. New commit message is "v1.8.0-alpha.0 Upgrading to v"

**Comment by JamesMessinger** [comment]
Weird.  I swore it was being appended, but the code doesn't lie.  It's definitely being pre-pended:

https://github.com/JS-DevTools/version-bump-prompt/blob/ce68d63dfb4b1c56068be58c21293e531ff21423/lib/index.js#L197-L199

I think the best solution is to go ahead and add the placeholder functionality that we discussed in Issue #29

**Comment by RTSchriner** [comment]
No worries, sounds good! 👍

**Comment by JamesMessinger** [comment]
I just released [**version 5.0.0**](https://github.com/JS-DevTools/version-bump-prompt/blob/master/CHANGELOG.md), which resolves this issue.

**Comment by RTSchriner** [comment]
Thanks!
