### ISSUE TITLE
Introduce a flag to skip preversion, version and postversion

### ISSUE THREAD

**Issue by sidtagirisa** [BigstickCarpet/version-bump-prompt#39]
If preversion, version and postversion are present in package.json, add an option to skip running those scripts.

**Comment by JamesMessinger** [comment]
That's a good idea.  I'd gladly welcome a PR to add this 👍

**Comment by sidtagirisa** [comment]
@JamesMessinger  I will try to look at that. Will let you know if I need help to set up in my local.

**Comment by sidtagirisa** [comment]
hi @JamesMessinger I have no permission for pushing new branch to repo. Can you give me access?

![image](https://user-images.githubusercontent.com/7590806/89019599-1fa56980-d350-11ea-921d-223ff8bc6b24.png)

**Comment by JamesMessinger** [comment]
@setshaft - [Submit a PR instead](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request), rather than pushing to the origin repo

**Comment by setshaft** [comment]
@JamesMessinger  I'm trying to do the same, i need to push a branch to create PR. Please look at the screenshot attached above, in that I'm trying to push changes on my own branch. I don't have permission to create a branch. 

Expert from the link attached above. 


_but you must have write permissions to create a branch._

**Comment by sidtagirisa** [comment]
@JamesMessinger ok I'll fork and raise pr 😊

**Comment by sidtagirisa** [comment]
@JamesMessinger I have submitted a PR for this, please take a look :)
